export const request = {
  description: "Ishola, Oluwasegun N SNBO-ITZ/CN",
  displayName: "Ishola, Oluwasegun N SNBO-PTIZ/C/ND",
  distinguishedName:
    "CN=NGOISC,OU=User Accounts Vista,OU=User Accounts,OU=User Directory,DC=africa-me,DC=shell,DC=com",
  email: "Oluwasegun.Ishola@shell.com",
  userID: "NGOISC",
  employeeId: null,
  firstName: "Oluwasegun",
  middleName: null,
  jobTitle: "Software Engineer",
  lastName: "Ishola",
  userName: "Oluwasegun.Ishola",
  ou: "SNBO",
  location: "Lagos",
  company: "Shell Nigeria Business Operations Ltd.",
  businessCategory: "IT",
  physicalDeliveryOfficeName: "LAG",
  officePhoneNumber: "+2348070262382",
  whenCreated: "2021-06-18T17:24:47",
  whenChanged: "2022-07-18T17:55:11",
  employmentType: "S",
  manager:
    "CN=WACCH0,OU=User Accounts Vista,OU=User Accounts,OU=User Directory,DC=africa-me,DC=shell,DC=com",
  managerCN: "WACCH0",
  refIndicator: "PTIZ/C/ND",
  userRole: {
    id: "1867645f-d1c7-46d5-ad5b-08da6b1cdd19",
    name: "Requestors",
  },
};
