export const request = {
  description: "Nwala, Karl U SNBO-ITZ/CN",
  displayName: "Nwala, Karl U SNBO-PTIZ/C/ND",
  distinguishedName:
    "CN=NGKNWI,OU=User Accounts Vista,OU=User Accounts,OU=User Directory,DC=africa-me,DC=shell,DC=com",
  email: "Karl.Nwala@shell.com",
  userID: "NGKNWI",
  employeeId: null,
  firstName: "Karl",
  middleName: null,
  jobTitle: "Software Engineer",
  lastName: "Nwala",
  userName: "Karl.Nwala",
  ou: "SNBO",
  location: "Lagos",
  company: "Shell Nigeria Business Operations Ltd.",
  businessCategory: "IT",
  physicalDeliveryOfficeName: "LAG",
  officePhoneNumber: "+2348070222526",
  whenCreated: "2021-06-16T17:59:00",
  whenChanged: "2022-07-17T14:59:13",
  employmentType: "S",
  manager:
    "CN=WACCH0,OU=User Accounts Vista,OU=User Accounts,OU=User Directory,DC=africa-me,DC=shell,DC=com",
  managerCN: "WACCH0",
  refIndicator: "PTIZ/C/ND",
};
