export const response = {
  data: [
    {
      id: "8c7b4736-bbd1-466b-7359-08da697d697e",
      refIndicator: "PTIZ/C/ND",
      displayName: "Nwala, Karl U SNBO-PTIZ/C/ND",
      userID: "NGKNWI",
      jobTitle: "Software Engineer",
      firstName: "Karl",
      lastName: "Nwala",
      middleName: null,
      officePhoneNumber: "+2348070222526",
      address: null,
      createdDate: "0001-01-01T00:00:00",
      roleId: "00000000-0000-0000-0000-000000000000",
      userRole: null,
      ou: "SNBO",
      employeeId: null,
      managerCN: "WACCH0",
      company: "Shell Nigeria Business Operations Ltd.",
      location: "Lagos",
      businessCategory: "IT",
      employmentType: "S",
      isActive: true,
      email: "Karl.Nwala@shell.com",
      userName: "Karl.Nwala",
    },
    {
      id: "1d56dfab-606a-42d2-ed6a-08da6a48ce48",
      refIndicator: "PTIZ/C/ND",
      displayName: "Ishola, Oluwasegun N SNBO-PTIZ/C/ND",
      userID: "NGOISC",
      jobTitle: "Software Engineer",
      firstName: "Oluwasegun",
      lastName: "Ishola",
      middleName: null,
      officePhoneNumber: "+2348070262382",
      address: null,
      createdDate: "0001-01-01T00:00:00",
      roleId: "00000000-0000-0000-0000-000000000000",
      userRole: null,
      ou: "SNBO",
      employeeId: null,
      managerCN: "WACCH0",
      company: "Shell Nigeria Business Operations Ltd.",
      location: "Lagos",
      businessCategory: "IT",
      employmentType: "S",
      isActive: true,
      email: "Oluwasegun.Ishola@shell.com",
      userName: "Oluwasegun.Ishola",
    },
    {
      id: "36c9a0d2-0acf-4668-8f72-08da6b06ed8a",
      refIndicator: "PTIZ/C/ND",
      displayName: "Ishola, Oluwasegun N SNBO-PTIZ/C/ND",
      userID: "NGOISC",
      jobTitle: "Software Engineer",
      firstName: "Oluwasegun",
      lastName: "Ishola",
      middleName: null,
      officePhoneNumber: "+2348070262382",
      address: null,
      createdDate: "0001-01-01T00:00:00",
      roleId: "00000000-0000-0000-0000-000000000000",
      userRole: null,
      ou: "SNBO",
      employeeId: null,
      managerCN: "WACCH0",
      company: "Shell Nigeria Business Operations Ltd.",
      location: "Lagos",
      businessCategory: "IT",
      employmentType: "S",
      isActive: true,
      email: "Oluwasegun.Ishola@shell.com",
      userName: "Oluwasegun.Ishola",
    },
  ],
  responseMessage: "Success",
  responseCode: 200,
};
