
export const response =
{
    "responseMessage": "SUCCESS",
    "responseCode": 200,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im9sdXdhc2VndW4uaXNob2xhIiwibmJmIjoxNjU4MDg0NzY1LCJleHAiOjE2NTgwODUzNjUsImlhdCI6MTY1ODA4NDc2NX0.HB1zd2HZT7OKM6T9E8bYFjdqHxhAfG3WiVf0u_MZTqU",
    "profile": {
        "refIndicator": null,
        "displayName": "Ishola, Oluwasegun N SNBO-PTIZ/C/ND",
        "userID": null,
        "jobTitle": "Software Engineer",
        "mobilePhoneNumber": null,
        "firstName": "Oluwasegun",
        "lastName": "Ishola",
        "middleName": null,
        "officePhoneNumber": "+2348070262382",
        "address": null,
        "lastLogonDate": "0001-01-01T00:00:00",
        "createdDate": "0001-01-01T00:00:00",
        "lastModifiedDate": "0001-01-01T00:00:00",
        "roleId": "00000000-0000-0000-0000-000000000000",
        "userRole": null,
        "photoData": null,
        "ou": "SNBO",
        "employeeId": null,
        "managerCN": "WACCH0",
        "shellGGDDepartmentNumber": "PTIZ/C/ND",
        "company": "Shell Nigeria Business Operations Ltd.",
        "location": "Lagos",
        "businessCategory": "IT",
        "employmentType": "S",
        "isActive": true,
        "id": "00000000-0000-0000-0000-000000000000",
        "userName": null,
        "normalizedUserName": null,
        "email": "Oluwasegun.Ishola@shell.com",
        "normalizedEmail": null,
        "emailConfirmed": false,
        "passwordHash": null,
        "securityStamp": null,
        "concurrencyStamp": "7f5c35e8-d854-4a3c-9397-395aee52cb30",
        "phoneNumber": null,
        "phoneNumberConfirmed": false,
        "twoFactorEnabled": false,
        "lockoutEnd": null,
        "lockoutEnabled": false,
        "accessFailedCount": 0
    }
}
