export const urlPaths = {
  home: "/home",
  dashboard: "/dashboard",
  roles: "/roles",
  approvals: "/approvals",
  profile: "/profile",
  products: {
    index: "/product",
    details: "/product/details",
  },
  wells: "/products/wells",
  upload: "/products/upload",
  hotdesk: "/products/hotdesk",
  users: "/users",
  admin: "/admin",
  report: "/report",
  logout: "/logout",
  wishlist: "/wishlist",
  ratings: "/ratings",
  orders: "/orders",
  auth: "/auth",
  /////
  loan: "/loanproduct",
  data: "/datamgt",
  warehouse: "/warehouseofficer",
  inventory: "/inventory",
  unclaimed: "/unclaimedproduct",
  updateapprovalroute: "/updateapprovalroute",
  itemspendingapproval: "/itemspendingapproval",
};
