export const urlPaths = {
  home: "/home",
  dashboard: "/dashboard",
  roles: "/dashboard/roles",
  menus: "/dashboard/menus",
  data: "/dashboard/data",
  approvals: "/dashboard/approvals",
  profile: "/dashboard/profile",
  products: {
    index: "/dashboard/product",
    details: "/dashboard/product/details",
  },
  wells: "/products/wells",
  upload: "/products/upload",
  hotdesk: "/products/hotdesk",
  users: "/users",
  admin: "/admin",
  report: "/report",
  logout: "/logout",
  wishlist: "/wishlist",
  ratings: "/ratings",
  orders: "/orders",
  auth: "/auth",
  loan: "/loanproduct",
  warehouse: "/warehouseofficer",
  inventory: "/inventory",
  unclaimed: "/unclaimedproduct",
  updateapprovalroute: "/updateapprovalroute",
  itemspendingapproval: "/itemspendingapproval",
};
